# Generated by Django 5.2.10 on 2026-02-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_corevalue_organizationprofile_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('highlight_stats', models.CharField(blank=True, help_text="Optional stats e.g. '2,500 children, 850+ volunteers'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order in the timeline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'year'],
            },
        ),
    ]
