# Generated by Django 5.2.10 on 2026-02-09 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_milestone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='program',
            name='gradient_color',
            field=models.CharField(default='from-vto-orange to-vto-orange-golden', help_text='Example: from-vto-orange to-vto-orange-golden', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='icon_class',
            field=models.CharField(default='fas fa-heart', help_text='Example: fas fa-book-open', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ProgramFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.program')),
            ],
        ),
    ]
