# Generated by Django 5.2.10 on 2026-02-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_program_options_program_gradient_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
