# Generated by Django 5.2.10 on 2026-05-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organizationprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default="Empowering Tomorrow's Leaders", max_length=100)),
                ('hero_title', models.CharField(default='Every Teen deserves a brighter future.', max_length=200)),
                ('hero_subtitle', models.TextField(default='We transform the lives of orphaned and underprivileged teens through education, mentorship, life skills, and a safe community where every young person can thrive.')),
                ('hero_image', models.ImageField(blank=True, help_text='Recommended size: 800x520px', null=True, upload_to='hero/')),
                ('years_of_impact', models.PositiveSmallIntegerField(default=15)),
                ('lives_supported', models.PositiveIntegerField(default=1200)),
                ('partners_count', models.PositiveSmallIntegerField(default=30)),
                ('primary_cta_text', models.CharField(default='Our Story', max_length=50)),
                ('primary_cta_url_name', models.CharField(default='about', max_length=100)),
                ('secondary_cta_text', models.CharField(default='Volunteer', max_length=50)),
                ('secondary_cta_url_name', models.CharField(default='volunteer', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Teen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teens/')),
                ('age', models.PositiveSmallIntegerField()),
                ('story', models.TextField(help_text='Short success story')),
                ('is_featured', models.BooleanField(default=False)),
                ('joined_date', models.DateField()),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='name',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='role',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
