# Generated by Django 5.2.10 on 2026-05-24 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfiguration_teen_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corevalue',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='organizationprofile',
            options={'verbose_name': 'Organization Profile', 'verbose_name_plural': 'Organization Profile'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='teen',
            options={'ordering': ['-joined_date', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='gradient_color',
        ),
        migrations.RemoveField(
            model_name='program',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_title',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile photo (square recommended)', null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, help_text='e.g., Donor, Volunteer, Parent', max_length=100),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='icon',
            field=models.CharField(help_text="Font Awesome icon class, e.g., 'fas fa-heart'", max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('donation', 'Donations'), ('volunteer', 'Volunteering'), ('child', 'Child Sponsorship'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='impactstat',
            name='icon',
            field=models.CharField(help_text="Font Awesome class, e.g., 'fas fa-heart'", max_length=50),
        ),
        migrations.AlterField(
            model_name='impactstat',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='impactstat',
            name='suffix',
            field=models.CharField(blank=True, help_text='Optional: +, %, K', max_length=10),
        ),
        migrations.AlterField(
            model_name='impactstat',
            name='value',
            field=models.CharField(help_text="Number or text, e.g., '15'", max_length=20),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='navigation_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size: 800x600px', null=True, upload_to='programs/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status', '-created_at'], name='core_contac_status_a0adbc_idx'),
        ),
        migrations.AddIndex(
            model_name='impactstat',
            index=models.Index(fields=['is_active', 'order'], name='core_impact_is_acti_078a67_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['order', 'year'], name='core_milest_order_efea56_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_published', 'show_in_navigation'], name='core_page_is_publ_1d3a50_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_active', 'order'], name='core_progra_is_acti_ee909c_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['is_active', 'order'], name='core_teamme_is_acti_3dc578_idx'),
        ),
        migrations.AddIndex(
            model_name='teen',
            index=models.Index(fields=['is_featured', '-joined_date'], name='core_teen_is_feat_2535cc_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_active', 'order'], name='core_testim_is_acti_a3ce38_idx'),
        ),
    ]
