# Generated by Django 5.2.10 on 2026-06-09 13:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_corevalue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('message', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="Font Awesome icon class (e.g., 'fas fa-home')", max_length=50)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Focus area description with rich text formatting')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Focus Area',
                'verbose_name_plural': 'Focus Areas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(help_text="e.g., '10,000+' or '50'", max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Detailed description with rich text formatting')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impact',
                'verbose_name_plural': 'Impacts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('partner_type', models.CharField(choices=[('corporate', 'Corporate Partner'), ('ngo', 'NGO Partner'), ('government', 'Government Partner'), ('community', 'Community Partner')], default='corporate', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('website_url', models.URLField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Partner description with rich text formatting')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='corevalue',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Core Value', 'verbose_name_plural': 'Core Values'},
        ),
        migrations.AddField(
            model_name='corevalue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for mission/vision section', null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title',
            field=models.CharField(blank=True, help_text="Specific job title (e.g., 'Executive Director')", max_length=100),
        ),
        migrations.AddField(
            model_name='teen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Core value description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(help_text='FAQ answer with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Milestone description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='mission',
            field=ckeditor.fields.RichTextField(help_text='Organization mission statement with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='vision',
            field=ckeditor.fields.RichTextField(help_text='Organization vision statement with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Page content with rich text formatting (images, links, etc.)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Program description with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Team member biography with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('board', 'Board Member'), ('staff', 'Staff'), ('volunteer', 'Volunteer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teen',
            name='story',
            field=ckeditor.fields.RichTextField(help_text='Success story with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Testimonial content with rich text formatting'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'is_active', 'order'], name='core_faq_categor_1779d9_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', '-created_at'], name='core_donati_status_d3fd83_idx'),
        ),
        migrations.AddIndex(
            model_name='impact',
            index=models.Index(fields=['is_active', 'order'], name='core_impact_is_acti_a08b62_idx'),
        ),
    ]
