# Generated by Django 5.2.10 on 2026-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_donation_focusarea_impact_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text="General role (e.g., 'Executive Director', 'Program Manager')", max_length=100),
        ),
    ]
