# Generated by Django 5.2.10 on 2026-06-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_teammember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='title',
        ),
    ]
