# Generated by Django 5.2.10 on 2026-06-09 15:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_teammember_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', ckeditor.fields.RichTextField(help_text='Organization history with rich text formatting')),
                ('mission', ckeditor.fields.RichTextField(help_text='Organization mission statement with rich text formatting')),
                ('vision', ckeditor.fields.RichTextField(help_text='Organization vision statement with rich text formatting')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for mission/vision section', null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Organization Profile',
                'verbose_name_plural': 'Organization Profile',
            },
        ),
        migrations.DeleteModel(
            name='OrganizationProfile',
        ),
    ]
