# Generated by Django 5.2.10 on 2026-01-16 17:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Child Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(help_text='Public display name for privacy', max_length=100, unique=True)),
                ('internal_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(19)])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active - In our care'), ('graduated', 'Graduated - Successfully transitioned'), ('reunited', 'Reunited - With family'), ('transferred', 'Transferred - To another program'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('date_admitted', models.DateField()),
                ('date_departed', models.DateField(blank=True, null=True)),
                ('background_summary', models.TextField(help_text='Public-friendly background (privacy protected)')),
                ('private_background', models.TextField(blank=True, help_text='Full background (staff only)')),
                ('current_needs', models.TextField(blank=True, help_text='Current needs for sponsorship')),
                ('interests', models.TextField(blank=True, help_text='Hobbies, interests, talents')),
                ('educational_level', models.CharField(blank=True, max_length=100)),
                ('career_aspirations', models.TextField(blank=True)),
                ('health_status', models.TextField(blank=True, help_text='General health information (staff only)')),
                ('special_needs', models.TextField(blank=True, help_text='Any special needs or disabilities')),
                ('is_sponsored', models.BooleanField(default=False)),
                ('sponsorship_needed', models.BooleanField(default=True)),
                ('sponsorship_amount', models.DecimalField(decimal_places=2, default=10000.0, help_text='Monthly sponsorship amount', max_digits=10)),
                ('photo_consent', models.BooleanField(default=False, help_text='Consent for photos')),
                ('story_consent', models.BooleanField(default=False, help_text='Consent for sharing story')),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('consent_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Staff notes')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False, help_text='Visible to public')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_children', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='children.childcategory')),
            ],
            options={
                'verbose_name_plural': 'Children',
                'ordering': ['display_order', 'code_name'],
            },
        ),
        migrations.CreateModel(
            name='ChildPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='children/photos/')),
                ('photo_type', models.CharField(choices=[('profile', 'Profile Photo'), ('activity', 'Activity Photo'), ('educational', 'Educational Photo'), ('portrait', 'Portrait'), ('other', 'Other')], default='activity', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by staff for display')),
                ('requires_blur', models.BooleanField(default=False, help_text='Face needs to be blurred')),
                ('blur_applied', models.BooleanField(default=False, help_text='Face blur has been applied')),
                ('can_display_publicly', models.BooleanField(default=False, help_text='Can be displayed on public website')),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='children.child')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('story_type', models.CharField(choices=[('background', 'Background Story'), ('achievement', 'Achievement'), ('milestone', 'Milestone'), ('update', 'Regular Update'), ('success', 'Success Story')], default='update', max_length=20)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt for listings')),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by staff for display')),
                ('can_display_publicly', models.BooleanField(default=False, help_text='Can be displayed on public website')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='children.child')),
                ('photos', models.ManyToManyField(blank=True, related_name='stories', to='children.childphoto')),
            ],
            options={
                'verbose_name_plural': 'Child Stories',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('update_type', models.CharField(choices=[('progress', 'Progress Report'), ('academic', 'Academic Update'), ('health', 'Health Update'), ('personal', 'Personal Growth'), ('event', 'Special Event'), ('holiday', 'Holiday Greeting')], max_length=20)),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('can_share_publicly', models.BooleanField(default=False)),
                ('sent_to_sponsors', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='children.child')),
                ('photos', models.ManyToManyField(blank=True, to='children.childphoto')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('need_type', models.CharField(choices=[('education', 'Education'), ('health', 'Healthcare'), ('food', 'Food & Nutrition'), ('clothing', 'Clothing'), ('shelter', 'Shelter'), ('extracurricular', 'Extracurricular Activities'), ('counseling', 'Counseling & Therapy'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_fully_funded', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Funding'), ('funded', 'Fully Funded'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Visible to public for sponsorship')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='children.child')),
            ],
            options={
                'ordering': ['priority', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_type', models.CharField(choices=[('full', 'Full Sponsorship'), ('partial', 'Partial Sponsorship'), ('education', 'Education Only'), ('health', 'Healthcare Only'), ('other', 'Other')], max_length=20)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('can_receive_updates', models.BooleanField(default=True)),
                ('can_send_messages', models.BooleanField(default=True)),
                ('communication_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Twice a Year'), ('annual', 'Yearly')], default='monthly', max_length=20)),
                ('is_recurring', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=20)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sponsorships', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='children.child')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sponsorships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['slug', 'is_published'], name='children_ch_slug_feae49_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['status', 'is_published'], name='children_ch_status_8d7f77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorship',
            unique_together={('child', 'sponsor', 'status')},
        ),
    ]
