# Generated by Django 5.2.10 on 2026-06-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
