# Generated by Django 5.2.10 on 2026-01-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
